2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting env: {}
2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '77af8f1b01a1c59ac8ae029f402b69f0094b9ca8'}
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:_log_setup():337] Logging user logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174057-25ri978g/logs/debug.log
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:_log_setup():338] Logging internal logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174057-25ri978g/logs/debug-internal.log
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():370] calling init triggers
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():392] re-initializing run, found existing run on stack: 38exczun
2021-07-11 17:40:57,512 INFO    MainThread:714 [wandb_run.py:finish():1293] finishing run sathvik/bloodraven66.github.io/38exczun
2021-07-11 17:40:57,513 INFO    MainThread:714 [jupyter.py:save_history():339] not saving jupyter history
2021-07-11 17:40:57,513 INFO    MainThread:714 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-07-11 17:40:57,513 INFO    MainThread:714 [wandb_init.py:_jupyter_teardown():269] cleaning up jupyter logic
2021-07-11 17:40:57,513 INFO    MainThread:714 [wandb_run.py:_atexit_cleanup():1593] got exitcode: 0
2021-07-11 17:40:57,513 INFO    MainThread:714 [wandb_run.py:_restore():1565] restore
2021-07-11 17:41:01,395 ERROR   MainThread:714 [wandb_run.py:_atexit_cleanup():1611] Problem finishing run
Traceback (most recent call last):
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1601, in _atexit_cleanup
    self._on_finish()
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1737, in _on_finish
    self.history._flush()
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 932, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 222, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/data_types.py", line 2210, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/data_types.py", line 2235, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/sdk/data_types.py", line 2160, in make_plot_media
    val = util.matplotlib_to_plotly(val)
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/util.py", line 415, in matplotlib_to_plotly
    required="plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`",
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/util.py", line 192, in get_module
    raise wandb.Error(required)
wandb.errors.Error: plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`
2021-07-11 17:41:01,398 INFO    MainThread:714 [wandb_init.py:init():419] starting backend
2021-07-11 17:41:01,398 INFO    MainThread:714 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-11 17:41:01,401 INFO    MainThread:714 [backend.py:ensure_launched():135] starting backend process...
2021-07-11 17:41:01,403 INFO    MainThread:714 [backend.py:ensure_launched():140] started backend process with pid: 1010
2021-07-11 17:41:01,404 INFO    MainThread:714 [wandb_init.py:init():424] backend started and connected
2021-07-11 17:41:01,417 INFO    MainThread:714 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-11 17:41:01,418 INFO    MainThread:714 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: list index out of range
2021-07-11 17:41:01,418 INFO    MainThread:714 [wandb_init.py:init():472] updated telemetry
2021-07-11 17:41:01,418 INFO    MainThread:714 [wandb_init.py:init():491] communicating current version
2021-07-11 17:41:02,247 INFO    MainThread:714 [wandb_init.py:init():496] got version response 
2021-07-11 17:41:02,248 INFO    MainThread:714 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-11 17:41:02,760 INFO    MainThread:714 [wandb_init.py:init():529] starting run threads in backend
2021-07-11 17:41:02,789 INFO    MainThread:714 [wandb_run.py:_console_start():1623] atexit reg
2021-07-11 17:41:02,790 INFO    MainThread:714 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2021-07-11 17:41:02,790 INFO    MainThread:714 [wandb_run.py:_redirect():1534] Wrapping output streams.
2021-07-11 17:41:02,792 INFO    MainThread:714 [wandb_run.py:_redirect():1558] Redirects installed.
2021-07-11 17:41:02,792 INFO    MainThread:714 [wandb_init.py:init():554] run started, returning control to user process
2021-07-11 17:45:32,758 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting env: {}
2021-07-11 17:45:32,758 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-11 17:45:32,758 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '77af8f1b01a1c59ac8ae029f402b69f0094b9ca8'}
2021-07-11 17:45:32,758 INFO    MainThread:714 [wandb_init.py:_log_setup():337] Logging user logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174532-3jtw8erx/logs/debug.log
2021-07-11 17:45:32,758 INFO    MainThread:714 [wandb_init.py:_log_setup():338] Logging internal logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174532-3jtw8erx/logs/debug-internal.log
2021-07-11 17:45:32,759 INFO    MainThread:714 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb35a781d30>
2021-07-11 17:45:32,759 INFO    MainThread:714 [wandb_init.py:init():370] calling init triggers
2021-07-11 17:45:32,759 INFO    MainThread:714 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-07-11 17:45:32,759 INFO    MainThread:714 [wandb_init.py:init():392] re-initializing run, found existing run on stack: 25ri978g
2021-07-11 17:45:32,760 INFO    MainThread:714 [wandb_run.py:finish():1293] finishing run sathvik/bloodraven66.github.io/25ri978g
