2021-07-11 17:40:41,981 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting env: {}
2021-07-11 17:40:41,982 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-11 17:40:41,982 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '77af8f1b01a1c59ac8ae029f402b69f0094b9ca8'}
2021-07-11 17:40:41,982 INFO    MainThread:714 [wandb_init.py:_log_setup():337] Logging user logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174041-38exczun/logs/debug.log
2021-07-11 17:40:41,982 INFO    MainThread:714 [wandb_init.py:_log_setup():338] Logging internal logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174041-38exczun/logs/debug-internal.log
2021-07-11 17:40:41,982 INFO    MainThread:714 [wandb_init.py:_jupyter_setup():288] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb38ec2b048>
2021-07-11 17:40:41,983 INFO    MainThread:714 [wandb_init.py:init():370] calling init triggers
2021-07-11 17:40:41,983 INFO    MainThread:714 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-07-11 17:40:41,983 INFO    MainThread:714 [wandb_init.py:init():419] starting backend
2021-07-11 17:40:41,983 INFO    MainThread:714 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-11 17:40:41,991 INFO    MainThread:714 [backend.py:ensure_launched():135] starting backend process...
2021-07-11 17:40:41,995 INFO    MainThread:714 [backend.py:ensure_launched():140] started backend process with pid: 923
2021-07-11 17:40:41,996 INFO    MainThread:714 [wandb_init.py:init():424] backend started and connected
2021-07-11 17:40:42,034 INFO    MainThread:714 [wandb_run.py:_label_probe_notebook():844] probe notebook
2021-07-11 17:40:42,035 INFO    MainThread:714 [wandb_run.py:_label_probe_notebook():851] Unable to probe notebook: list index out of range
2021-07-11 17:40:42,035 INFO    MainThread:714 [wandb_init.py:init():472] updated telemetry
2021-07-11 17:40:42,035 INFO    MainThread:714 [wandb_init.py:init():491] communicating current version
2021-07-11 17:40:43,192 INFO    MainThread:714 [wandb_init.py:init():496] got version response 
2021-07-11 17:40:43,192 INFO    MainThread:714 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-11 17:40:43,893 INFO    MainThread:714 [wandb_init.py:init():529] starting run threads in backend
2021-07-11 17:40:43,922 INFO    MainThread:714 [wandb_run.py:_console_start():1623] atexit reg
2021-07-11 17:40:43,922 INFO    MainThread:714 [wandb_run.py:_redirect():1497] redirect: SettingsConsole.WRAP
2021-07-11 17:40:43,923 INFO    MainThread:714 [wandb_run.py:_redirect():1534] Wrapping output streams.
2021-07-11 17:40:43,924 INFO    MainThread:714 [wandb_run.py:_redirect():1558] Redirects installed.
2021-07-11 17:40:43,924 INFO    MainThread:714 [wandb_init.py:init():554] run started, returning control to user process
2021-07-11 17:40:43,925 ERROR   MainThread:714 [util.py:get_module():190] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "/home/sathvik/.local/lib/python3.6/site-packages/wandb/util.py", line 185, in get_module
    return import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly'
2021-07-11 17:40:44,068 INFO    MainThread:714 [wandb_init.py:_pause_backend():250] pausing backend
2021-07-11 17:40:44,068 INFO    MainThread:714 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-07-11 17:40:57,486 INFO    MainThread:714 [wandb_init.py:_resume_backend():259] resuming backend
2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting env: {}
2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-11 17:40:57,510 INFO    MainThread:714 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '77af8f1b01a1c59ac8ae029f402b69f0094b9ca8'}
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:_log_setup():337] Logging user logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174057-25ri978g/logs/debug.log
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:_log_setup():338] Logging internal logs to /home/sathvik/Documents/bloodraven66.github.io/wandb/run-20210711_174057-25ri978g/logs/debug-internal.log
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():370] calling init triggers
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-07-11 17:40:57,511 INFO    MainThread:714 [wandb_init.py:init():392] re-initializing run, found existing run on stack: 38exczun
2021-07-11 17:40:57,512 INFO    MainThread:714 [wandb_run.py:finish():1293] finishing run sathvik/bloodraven66.github.io/38exczun
